TRUNCATE TABLE
  transfers,
  transport_states,
  transports_coordinates,
  alerts,
  measurements,
  devices,
  usr_user_role,
  usr_role_server_permission,
  usr_firebase_token,
  containers_lots,
  lots,
  containers,
  transports,
  vehicles,
  locations,
  bills,
  usr_user,
  usr_role,
  usr_server_permission,
  companies,
  plan_prices,
  plans,
  products
RESTART IDENTITY CASCADE;